# System Set-Up
language: cpp

branches:
  only:
    - master

jobs:
  include:
    - os: linux
      dist: focal
      compiler: gcc
      python: 3.8
      name: "Linux Focal Python 3.8"
      env:
        - CC=gcc-9
        - CXX=g++-9
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-9
            - g++-9
            - cmake
            - libcfitsio-dev
            - libhealpix-cxx-dev
          update: true
    - os: osx
      osx_image: xcode12
      language: shell
      env: PYTHON_VERSION=3.8
      name: "macOS 10.15 AppleClang Python 3.8"
      addons:
        homebrew:
          taps: sfarrens/sf
          packages:
            - cmake
            - cfitsio
            - pkgconfig
            - healpix
            - bigmac
          update: true

before_install:
    - if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get update; fi
    - if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo updatedb; fi
    - if [ $TRAVIS_OS_NAME = 'osx' ];
      then curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh;
      else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - if [ $TRAVIS_OS_NAME = 'linux' ]; then
        export CPLUS_INCLUDE_PATH=$(cd /opt/python/3.*/include/python3.*; pwd);
      fi
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - if [ $TRAVIS_OS_NAME = 'osx' ];
      then conda create -n testenv --yes pip python=$PYTHON_VERSION;
      else conda create -n testenv --yes pip python=$TRAVIS_PYTHON_VERSION;
      fi
    - source activate testenv
    - pip install --upgrade pip

install:
    - python setup.py install

script:
    - python -c "import pycs; print(pycs.__version__)"
