include $(SAPDEV)/Var.inc

SRC = $(SAPDEV)/devl/mga/2d

EXPORT = MR_Sat.h \
	Curvelet.h \
	MRBase.h \
	PrimeNumber.h \
	RidNoise.h \
	MBase.h \
	PCur.h  \
	RadNoise.h  \
	Ridgelet.h \
	CurContrast.h \
 	CB_MCA.h

OBJECTS = MR_Sat.o \
	Curvelet.o \
	MBase.o \
	MRBase.o \
	PCur.o \
	PrimeNumber.o \
	RadNoise.o \
	RidFilter.o \
	RidNoise.o \
	Ridgelet.o\
	CurContrast.o \
	CB_MCA.o

LIBRARY = $(LIBFILE)/$(LIB_MGA2D)

all: newlib

include $(SAPDEV)/makefile.sys
