name: CI

on:
  pull_request:
    branches:
     - develop
     - master
     - main

jobs:
  test-full:
    name: Full Test Suite
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ["3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check Python Version
        run: python --version

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libarmadillo-dev libcfitsio-dev libfftw3-dev libgsl-dev libhealpix-cxx-dev 
          sudo apt-get install -y pkg-config

      - name: Install macOS Dependencies
        if: runner.os == 'macOS'
        run: |
          brew tap sfarrens/sf
          brew install armadillo bigmac cfitsio fftw gsl healpix libomp

      - name: Install Package
        run: |
          python -m pip install ".[test]"

      - name: Run Tests
        run: |
          python -m pytest

  linter-check:
    name: Black Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Black formatting
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
