name: CI

on:
  pull_request:
    branches:
     - develop
     - master
     - main

jobs:
  test-full:
    name: Full Test Suite
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: [3.9]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Conda with Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: Check Conda
        shell: bash -l {0}
        run: |
          conda info
          conda list
          python --version

      - name: Install Linux Dependencies
        shell: bash -l {0}
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libarmadillo-dev libfftw3-3 libgsl-dev pkg-config

      - name: Install macOS Dependencies
        shell: bash -l {0}
        if: runner.os == 'macOS'
        run: |
          brew tap sfarrens/sf
          brew install armadillo bigmac fftw gsl libomp

      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          python --version
          python -m pip install --upgrade pip

      - name: Run Tests
        shell: bash -l {0}
        run: |
          python setup.py test
